GET http://localhost:4000/posts HTTP/1.1

###

POST http://localhost:4000/posts HTTP/1.1
content-type: application/json

{
    "title": "First Post"
}

###

POST http://127.0.0.1:65514/posts
content-type: application/json

{
    "title": "New POST"
}

###

POST http://localhost:4005/posts
content-type: application/json

{
    "type": "TEST",
    "data": {}
}